### ISSUE TITLE
Can this output SVG?

### ISSUE THREAD

**Issue by dmvaldman** [roice3/TilingBot#1]
I'd like to laser cut these.

**Comment by roice3** [comment]
Hi David,

Unfortunately, not at the moment. TilingBot does per-pixel raster calculations but my [MagicTile](http://roice3.org/magictile) program takes a different approach and has an export-to-SVG function. Depending on which tilings/projections you want, you may be able to get some nice SVG files to laser cut with it.

I'll add SVG creation to my running wishlist for TilingBot. It won't be too difficult to support but I can't promise when it will happen. Let me know which tiling in particular you'd like to start with so I can use it as a test case.

Thank you for the inquiry!

Roice

**Comment by dmvaldman** [comment]
Ah thanks, I'll take a look at your MagicTile project as well. If SVG exporting does become a feature, let me know! I'll close this "issue".

Great work.

**Comment by ChristopherKing42** [comment]
@dmvaldman You probably already know this, but there are tracing algorithms that can convert raster to svg. I'm sure they'd work nicely on these images.
